### ISSUE TITLE
Anomalous ec2 instance doesn't get destroyed as part of the "python3 cobra.py aws destroy --scenario scenario-1" command

### ISSUE THREAD

**Issue by amit-schnitzer** [PaloAltoNetworks/cobra-tool#12]
## Describe the bug

During the installation, an ec2 machine gets deployed not using Pulumi but using the "aws ec2 run-instances..." command but when the environment gets destroyed, the above instance doesn't get destroyed and thus left running and unattended.
This is not efficient and might incur unneeded costs much after the environment is used.  

## Expected behavior

environment gets cleaned completely, restoring customer account similar to how it was before running the lab 
## Current behavior

ec2 machine is left running even after the lab is destroyed 

## Possible solution

Add a script to remove that instance when destroyed 

## Steps to reproduce

1. Create the environment - "python3 cobra.py aws launch --simulation" choosing scenario1 
2. Wait until all 3 instances gets created (cobra-attacker, cobra-webserver and cobra-anomalous)
3. Destroy the environment - "python3 cobra.py aws destroy --scenario scenario-1"
4. Check the AWS account and you'll notice the anomalous instance still up and running even after it has been destroyed 

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by sgordon46** [comment]
@anandtiwarics this issue can be closed.
