### ISSUE TITLE
Using Pulumi

### ISSUE THREAD

**Issue by sgordon46** [PaloAltoNetworks/cobra-tool#9]
I had a question around what else is needed to use Pulumi.  It says to install, but are there any other requirements. 

I'd suggest adding this to the README is something else is needed. 

I'm getting an error when trying to run simulation 1
`ModuleNotFoundError: No module named 'pulumi'`

**Comment by aseto-pan** [comment]
Concur. I have never touched Pulumi before this and I can't get it working. I setup and account and I'm getting this error when trying to run AWS scenario
![Uploading Screenshot 2024-07-02 at 2.41.35 PM.png…]()

**Comment by sgordon46** [comment]
@aseto-pan I'm updating the readme to include some more details on what is needed.
